# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_belt', '0002_trip_tripdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='startdate',
            new_name='start_date',
        ),
    ]
