# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_belt', '0004_auto_20170927_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetails',
            name='users',
        ),
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='tripusers', to='django_belt.User'),
        ),
    ]
