# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_belt', '0005_auto_20170927_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='planned', to='django_belt.User'),
        ),
    ]
