# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_belt', '0006_trip_planner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='users',
        ),
    ]
